using UdonSharp;
using UnityEngine;
using UnityEngine.UI;
using VRC.SDK3.Rendering;
using VRC.SDKBase;

[UdonBehaviourSyncMode(BehaviourSyncMode.None)]
public class SabaLlamaRunner : UdonSharpBehaviour
{
    [Header("Input / output")]
    public InputField input;
    public Text output;
    public string prompt = "Once upon a time";
    [Range(1, 64)] public int maxNewTokens = 32;
    [Range(1, 8)] public int passesPerFrame = 1;
    [Tooltip("Local GPU allocation limit, excluding the weight texture.")]
    public int maxWorkingMiB = 128;
    [Header("Generated by the SabaProps Llama editor")]
    public Texture2D weights;
    public Material[] templates;
    public int[] inputA, inputB, targets, widths, heights;
    public int context, vocabulary, resultTarget;
    public string[] pieces, sortedPieces;
    public int[] sortedIds, byteTokens;
    public float[] scores;

    private RenderTexture[] buffers;
    private Material[] materials;
    private Color[] result = new Color[1];
    private int[] promptTokens = new int[1026];
    private int tokenCount, characterIndex, mergeIndex, bestIndex, bestId;
    private float bestScore;
    private string text;
    private int phase; // 0 idle, 1 characters, 2 merges, 3 inference
    private int position, token, step, generated, budget;
    private bool waiting, discardReadback;
    private byte[] generatedBytes = new byte[65536];
    private int generatedLength;
    private string displayText;

    public override void Interact()
    {
        if (phase != 0 || waiting) StopGeneration();
        else Generate();
    }

    public void Generate()
    {
        // A readback carries no application request ID. Drain it before permitting reuse.
        if (waiting || phase != 0) return;
        text = input != null ? input.text : prompt;
        if (text == null || text.Length > 256) { Report("入力は256文字以内にしてください。"); return; }
        if (!InitializeGpu()) return;
        budget = Mathf.Clamp(maxNewTokens, 1, 64);
        position = 0; step = 0; generated = 0; generatedLength = 0;
        displayText = text;
        tokenCount = 1; promptTokens[0] = 1; characterIndex = 0;
        if (text.Length > 0)
        {
            int space = FindPiece(" ");
            if (space < 0) { Report("空白tokenがありません。"); return; }
            promptTokens[tokenCount++] = space;
        }
        phase = 1;
        Report("入力をtokenizeしています。");
    }

    public void StopGeneration()
    {
        phase = 0;
        if (waiting) discardReadback = true;
        Report(displayText + "\n[停止]");
    }

    private bool InitializeGpu()
    {
        if (buffers != null) return true;
        if (weights == null || templates == null || templates.Length == 0 ||
            widths == null || heights == null || widths.Length != heights.Length ||
            inputA == null || inputB == null || targets == null ||
            templates.Length != inputA.Length || templates.Length != inputB.Length || templates.Length != targets.Length ||
            pieces == null || scores == null || sortedIds == null || sortedPieces == null ||
            pieces.Length != vocabulary || scores.Length != vocabulary || sortedIds.Length != vocabulary || sortedPieces.Length != vocabulary ||
            byteTokens == null || byteTokens.Length != 256 || context < 1 || context > 256 ||
            resultTarget < 0 || resultTarget >= widths.Length)
        { Report("生成されたモデル設定が不正です。"); return false; }
        if (!SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.ARGBFloat) ||
            !SystemInfo.SupportsTextureFormat(TextureFormat.RFloat) || !SystemInfo.supportsAsyncGPUReadback ||
            weights.width > SystemInfo.maxTextureSize || weights.height > SystemInfo.maxTextureSize)
        { Report("このGPUは必要なFP32 texture / readbackに対応していません。"); return false; }
        long bytes = 0;
        for (int i = 0; i < widths.Length; i++)
        {
            if (widths[i] < 1 || heights[i] < 1 || widths[i] > SystemInfo.maxTextureSize || heights[i] > SystemInfo.maxTextureSize)
            { Report("RenderTextureの寸法が不正です。"); return false; }
            bytes += (long)widths[i] * heights[i] * 16;
        }
        if (maxWorkingMiB < 1 || bytes > (long)maxWorkingMiB * 1048576)
        { Report("GPU作業メモリの上限を超えています。"); return false; }
        for (int i = 0; i < templates.Length; i++)
        {
            if (templates[i] == null || !templates[i].shader.isSupported || targets[i] < 0 || targets[i] >= widths.Length ||
                inputA[i] < -1 || inputA[i] >= widths.Length || inputB[i] < -1 || inputB[i] >= widths.Length ||
                targets[i] == inputA[i] || targets[i] == inputB[i])
            { Report("GPU演算の設定が不正です。"); return false; }
        }
        buffers = new RenderTexture[widths.Length];
        materials = new Material[templates.Length];
        for (int i = 0; i < widths.Length; i++)
        {
            buffers[i] = new RenderTexture(widths[i], heights[i], 0, RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.Linear);
            buffers[i].filterMode = FilterMode.Point;
            buffers[i].wrapMode = TextureWrapMode.Clamp;
            buffers[i].useMipMap = false;
            buffers[i].antiAliasing = 1;
            if (!buffers[i].Create()) { ReleaseGpu(); Report("GPUメモリを確保できませんでした。"); return false; }
        }
        for (int i = 0; i < templates.Length; i++)
        {
            materials[i] = new Material(templates[i]);
            if (inputA[i] >= 0) materials[i].SetTexture("_A", buffers[inputA[i]]);
            if (inputB[i] >= 0) materials[i].SetTexture("_B", buffers[inputB[i]]);
        }
        return true;
    }

    private int FindPiece(string piece)
    {
        int low = 0, high = sortedPieces.Length - 1;
        while (low <= high)
        {
            int middle = low + (high - low) / 2;
            int comparison = string.CompareOrdinal(sortedPieces[middle], piece);
            if (comparison == 0) return sortedIds[middle];
            if (comparison < 0) low = middle + 1;
            else high = middle - 1;
        }
        return -1;
    }

    private void Update()
    {
        if (waiting || phase == 0) return;
        if (phase == 1)
        {
            // Bound work per frame, including the tokenizer's preprocessing.
            for (int batch = 0; batch < 8 && characterIndex < text.Length; batch++)
            {
                int length = 1;
                int first = text[characterIndex];
                if (first >= 0xD800 && first <= 0xDBFF && characterIndex + 1 < text.Length)
                {
                    int second = text[characterIndex + 1];
                    if (second >= 0xDC00 && second <= 0xDFFF) length = 2;
                }
                string piece = text.Substring(characterIndex, length);
                characterIndex += length;
                int id = FindPiece(piece);
                if (id >= 0) promptTokens[tokenCount++] = id;
                else
                {
                    byte[] bytes = System.Text.Encoding.UTF8.GetBytes(piece);
                    for (int i = 0; i < bytes.Length; i++)
                    {
                        id = byteTokens[bytes[i]];
                        if (id < 0) { phase = 0; Report("入力に必要なbyte tokenがありません。"); return; }
                        promptTokens[tokenCount++] = id;
                    }
                }
            }
            if (characterIndex >= text.Length) { BeginMergeScan(); phase = 2; }
            return;
        }
        if (phase == 2)
        {
            for (int batch = 0; batch < 32 && mergeIndex + 1 < tokenCount; batch++, mergeIndex++)
            {
                int id = FindPiece(pieces[promptTokens[mergeIndex]] + pieces[promptTokens[mergeIndex + 1]]);
                if (id >= 0 && scores[id] > bestScore)
                { bestScore = scores[id]; bestIndex = mergeIndex; bestId = id; }
            }
            if (mergeIndex + 1 < tokenCount) return;
            if (bestIndex >= 0)
            {
                promptTokens[bestIndex] = bestId;
                for (int i = bestIndex + 1; i < tokenCount - 1; i++) promptTokens[i] = promptTokens[i + 1];
                tokenCount--; BeginMergeScan(); return;
            }
            if (tokenCount > context) { phase = 0; Report("入力がcontext上限を超えています。"); return; }
            token = promptTokens[0]; phase = 3;
            Report(displayText + "\n[生成中]");
            return;
        }
        int count = Mathf.Clamp(passesPerFrame, 1, 8);
        for (int pass = 0; pass < count && step < materials.Length; pass++)
        {
            if (!buffers[targets[step]].IsCreated()) { phase = 0; ReleaseGpu(); Report("GPU bufferが失われました。再実行してください。"); return; }
            materials[step].SetInt("_Position", position);
            materials[step].SetInt("_Token", token);
            VRCGraphics.Blit(Texture2D.blackTexture, buffers[targets[step]], materials[step]);
            step++;
        }
        if (step < materials.Length) return;
        step = 0;
        if (position + 1 < tokenCount)
        {
            position++; token = promptTokens[position]; return;
        }
        waiting = true;
        VRCAsyncGPUReadback.Request(buffers[resultTarget], 0, this);
    }

    private void BeginMergeScan()
    {
        mergeIndex = 1; bestIndex = -1; bestId = -1; bestScore = float.NegativeInfinity;
    }

    public void OnAsyncGpuReadbackComplete(VRCAsyncGPUReadbackRequest request)
    {
        if (!waiting) return;
        waiting = false;
        if (discardReadback) { discardReadback = false; if (!gameObject.activeInHierarchy) ReleaseGpu(); return; }
        if (request.hasError || !request.TryGetData(result)) { phase = 0; Report("GPU readbackに失敗しました。"); return; }
        if (result[0].b < 0.5f || float.IsNaN(result[0].r) || float.IsInfinity(result[0].r))
        { phase = 0; Report("推論結果が有限値ではありません。"); return; }
        int next = (int)result[0].g;
        if (next < 0 || next >= vocabulary) { phase = 0; Report("生成token IDが不正です。"); return; }
        if (next == 1 || next == 2) { phase = 0; Report(displayText); return; }
        string piece = pieces[next];
        if (token == 1 && piece.StartsWith(" ")) piece = piece.Substring(1);
        byte[] bytes;
        int byteValue = -1;
        for (int i = 0; i < 256; i++) if (byteTokens[i] == next) { byteValue = i; break; }
        if (byteValue >= 0) { bytes = new byte[1]; bytes[0] = (byte)byteValue; }
        else bytes = System.Text.Encoding.UTF8.GetBytes(piece);
        if (generatedLength + bytes.Length > generatedBytes.Length) { phase = 0; Report(displayText + "\n[出力上限]"); return; }
        for (int i = 0; i < bytes.Length; i++) generatedBytes[generatedLength++] = bytes[i];
        displayText = text + System.Text.Encoding.UTF8.GetString(generatedBytes, 0, generatedLength);
        generated++;
        position++;
        token = next;
        if (generated >= budget || position >= context) { phase = 0; Report(displayText + "\n[生成上限]"); }
        else Report(displayText + "\n[生成中]");
    }

    private void Report(string message)
    {
        if (output != null) { output.supportRichText = false; output.text = message; }
        else Debug.Log("[SabaProps Llama] " + message);
    }

    private void OnDisable()
    {
        phase = 0;
        if (waiting) discardReadback = true;
        else ReleaseGpu();
    }

    private void OnDestroy() { ReleaseGpu(); }

    private void ReleaseGpu()
    {
        if (materials != null) for (int i = 0; i < materials.Length; i++) if (materials[i] != null) Destroy(materials[i]);
        if (buffers != null) for (int i = 0; i < buffers.Length; i++) if (buffers[i] != null) { buffers[i].Release(); Destroy(buffers[i]); }
        materials = null; buffers = null;
    }
}
